# Site settings
author: Chase Ure
title: “Why did you decide to study Software Engineering?”
header-img: img/home-bg.png
email: urefast@msn.com
copyright_name: Chase Ure
description: > # this means to ignore newlines until "baseurl:"
  Engineering Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Cure3

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
